# Todo List:
# - Move librpcs3 compilation away (or add ccache here) because the compilation is ridiculously slow
# - Do not use legacy CMake scripts (figure out how)

name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      shouldrelease:
          description: Create release
          type: boolean
      releasetag:
        description: Enter the tag name
        type: string
      releasetype:
        description: Make it prerelease
        type: boolean
      islatest:
        description: Mark as latest
        type: boolean
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
          root-reserve-mb: 16384
          swap-size-mb: 16384
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        lfs: true

    - name: Setup CCache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Setup Gradle Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-android-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-android-
            
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept licenses
      run: |
        yes | sdkmanager --licenses

    - name: Install packages
      run: yes | sdkmanager "cmake;3.31.5"

    - name: Download gradlew binaries
      run: ./gradlew

    - name: Build with Gradle
      env: 
        CMAKE_C_COMPILER_LAUNCHER: "ccache"
        CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
      run: ./gradlew build

    - name: Build release artifacts
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name != 'workflow_dispatch' }}
      with:
        name: rpcs3-build
        path: |
          app/build/outputs/apk/release/*

    - name: Create release
      uses: softprops/action-gh-release@v2
      if: ${{ inputs.shouldrelease }}
      with:
        prerelease: ${{ inputs.releasetype }}
        tag_name: ${{ inputs.releasetag }}
        make_latest: ${{ inputs.islatest }}
        # body: 'Some release text body if needed'
        # body_path: or/as/file.md
        files: |
          app/build/outputs/apk/release/rpcs3-release.apk
